### ISSUE TITLE
Trying to initialize the `Main` module with an unexpected flag.

### ISSUE THREAD

**Issue by puruzio** [ohanhi/elm-taco#2]
I believe elm-reactor doesn't support flags (https://github.com/elm-lang/elm-reactor/issues/199), and I get the following error when I try to run the example code. I think it's odd that README suggests the use of elm-reactor. Is there an easy workaround that I'm missing here?

```
Oops! Something went wrong when starting your Elm program.

Trying to initialize the `Main` module with an unexpected flag.
I tried to convert it to an Elm value, but ran into this problem:

Expecting an object with a field named `currentTime` but instead got: undefined
```

**Comment by ohanhi** [comment]
@puruzio I think you missed the part of the README saying you should navigate to http://localhost:8000/index.html, not Main.elm. Or do you get the same error even on index.html?

**Comment by puruzio** [comment]
You are absolutely right. Thanks.
