### ISSUE TITLE
ports and subscriptions in SharedSate file

### ISSUE THREAD

**Issue by UlisesVD** [ohanhi/elm-taco#7]
it's possible to use ports in the SharedState file? I'm using firebase auth and want to saved the data of the user in sharedstate but I need to use ports but don't not what to do.
I try to added the ports directly in the sharedstate file but when I try to call it my port can't be find.

**Comment by ohanhi** [comment]
I assume you changed it to be a `port module` at that point. My guess is that the way you're trying to call the port is incorrect. In any case this is not an issue with this repository. Maybe you could ask for help on the Elm Slack. You can join here: https://elmlang.herokuapp.com/
