### ISSUE TITLE
subscriptions 

### ISSUE THREAD

**Issue by ikrizanovic** [ohanhi/elm-taco#8]
how do i set subscriptions in subpages? 
i do need it for AWS Cognito signin. thanks.

**Comment by ohanhi** [comment]
You can define subscriptions in any module, including subpages. Just make sure to add them to the subscriptions in Main.elm as well. To me, signing in sounds like a top-level thing though.

I'd suggest asking this on the Elm Slack. People are very friendly and helpful there.

**Comment by ikrizanovic** [comment]
Hi,
I am stucked for days with the same problem: how to set subscription in Settigs.elm subpage app using excellent https://github.com/ohanhi/elm-shared-state/ Hanhinen's example.

I have tried to find a tip on slack and I did get the answers, but
I couldn't implement it in the code. I immediately run into type issues.
Would it be possible, to get the answer like:

add that code in Main.elm 
and 
this code in Settings.elm and you have a subscription . Please. The Sub.message is defined in Settings.elm. 

I like the app, and have all I need, but without subscription I can not use it to implement my use case.
Thanks a lot.
ivan

**Comment by ohanhi** [comment]
Well it's pretty hard to give concrete code examples without knowing the rest of your code, but here's the pipework you need to do:

Main.elm
```elm
       , subscriptions =
            \_ ->
                Sub.batch
                    [ Time.every 1000 TimeChange
                    , Router.subscriptions
                    ]
```

Router.elm
```elm
subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.map SettingsMsg (Settings.subscriptions (model.settingsModel))
```

Settings.elm
```elm
subscriptions : Model -> Sub Msg
subscriptions model =
    -- (your wanted subscription)
```

**Comment by ikrizanovic** [comment]
Thank you very much for your time and effort. I do appreciate it a lot. However I do have type mismatch problem again:

-- TYPE MISMATCH --------------- E:\svn\trunk\aws\elm-shared-state\src\Routing\Router.elm

The 2nd argument to `map` is not what I expect:

376|     Sub.map SettingsMsg Settings.subscriptions
                             ^^^^^^^^^^^^^^^^^^^^^^
This `subscriptions` value is a:

    Settings.Model -> Sub Settings.Msg

But `map` needs the 2nd argument to be:

    Sub Settings.Msg

What i do wrong?
ivan

**Comment by ohanhi** [comment]
Oh well the error says it pretty clearly. `subscriptions` is a function that expects the Settings' model. I updated the previous comment.

**Comment by ikrizanovic** [comment]
Hi Ossi,

Thank you for your answer and your time. I was very pleased to see it and I started immediately implementing the solution. I am probably annoying you and my knowledge of Elm appears to be poor, but I would like to have subscriptions working.

However, when I try to implement it I still have the issue.

Changes in Router.elm compile fine, but calling 

       , subscriptions =
            \_ ->
                Sub.batch
                    [ Time.every 1000 TimeChange
                    , Router.subscriptions
 
from Main.elm gives:

-- TYPE MISMATCH --------------- E:\svn\trunk\aws\elm-shared-state\src\Main.elm


The 2nd element of this list does not match all the previous elements:

27|                     [ Time.every 1000 TimeChange
28|>                    , Router.subscriptions
29|                     ]

This `subscriptions` value is a:

    Router.Model -> Sub Router.Msg

But all the previous elements in the list are:

    Sub Msg

If I comment Time subscriptions I am getting:


-- TYPE MISMATCH --------------- E:\svn\trunk\aws\elm-shared-state\src\Main.elm

The 1st argument to `batch` is not what I expect:

26|                 Sub.batch
27|>                    [ --Time.every 1000 TimeChange
28|>                    Router.subscriptions
29|>                    ]

This argument is a list of type:

    List (Router.Model -> Sub Router.Msg)

But `batch` needs the 1st argument to be:

    List (Sub msg)




Could you somehow find time to give me a working solution? In Settings.elm I have just:


subscriptions : Model -> Sub Msg
subscriptions model =
    -- (your wanted subscription)
    let
        _ = Debug.log "Settings.elm" model
 
    in
    Sub.none
 
I do know what to do next, after I get Settings.elm subscribed to something.


Thanks many times again.
Ivan

**Comment by ohanhi** [comment]
I'm sorry but we have to stop doing this. This is really is not the place nor the medium for debugging your code, and I feel like I have tried to help you out regardless. Please put your code up somewhere in its entirety and then ask people on the Slack channels to help. The error you are getting is another place where a `Sub.map` would be needed but I really don't have the time or the energy to write that out for you. Best of luck!
